name: OIDC role deployment pipeline

on:
  push:
    # branches-ignore: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  # running-checkov:
  #   runs-on: ${{ vars.RUNNER_TAG }}
  #   steps:
  #     - name: SSH setup
  #       uses: manoj-vkt/ssh-action@V1.0
  #       with:
  #         private_key: ${{ secrets.SSH_KEY }}
  #     - name: Run Checkov
  #       uses: manoj-vkt/checkov-action@V1.0

  aws-deployment-to-536697232936:
    runs-on: ${{ vars.RUNNER_TAG }}
    # needs:
    #   - running-checkov
    steps:
      - name: checking out to repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: SSH setup
        uses: manoj-vkt/ssh-action@V1.0
        with:
          private_key: ${{ secrets.SSH_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRECT }}
          role-to-assume: ${{ secrets.ACCOUNT_ROLE_TO_ASSUME }}
      - name: Terraform apply
        uses: manoj-vkt/terraform-action@V1.0
        with:
          terraform_version: "1.6.6"
          account_setup_directory: "cloud_infrastructure"
          environment: "dev"
          tf_vars_file: "tfvars/account-536697232936.tfvars"
          config_file: "backend_service_config.hcl"

